### PR TITLE
Simple WebUI for the project

### PR DESCRIPTION
**Pull request by VatsaDev**
While there is a colab mentioned at #6 , the project has no UI whatsoever.

I've built upon the vLLM in the colab for a WebUI powered by Flask, with a custom front end currently based on text-generation. Its based on the current provided checkpoint, and should work for all future ones 

https://colab.research.google.com/drive/17oF4DXWRwU9zz_JhZ3DL62R8-fj2N3ka?usp=sharing

right now the frontend is at my github repo, [VatsaDev/tinyLlamaWebUI](https://github.com/VatsaDev/tinyLlamaWebUI) let me know if you want me to move it to this repo

### CODE REVIEW

**Comment by jzhang38** [comment]
We are exploring some suitable chat UI and fine-tuning methods. What we have in mind is to follow [OpenChat](https://github.com/jzhang38/OpenChat). I will leave this pull request here for now.

**Comment by Green-Sky** [comment]
> OpenChat

... links to private/non-existing repo :laughing:

**Comment by VatsaDev** [comment]
Oh I do plan to make this a chat UI, an I will be changing the website for that as soon as a `tinyLlama-chat` model exists. Its just a text-generation model for now, as the tinyLlama checkpoint only does text generation.

**Comment by jzhang38** [comment]
@VatsaDev @Green-Sky Thanks for pointing that out. I have updated my comment.

**Comment by VatsaDev** [comment]
Closing this PR for the Real UI at #30

**Pull request closed without merging**
