### PR TITLE
Working Chat Demo

### PR DESCRIPTION
**Pull request by VatsaDev**
@jzhang38 

saw the Chat Demo wasn't working, So I made the Chat WebUI for the model, like how we discussed at the Old Pull, its similar to [openchat](https://openchat.team) for UI, working on all the side features, but the main thing is working, there's a chat between User and Bot.

Colab - https://colab.research.google.com/drive/1OaWYiHBt-nkSNCik6H0lhAWcpLCYvauq?usp=sharing

~~Its Wonky, since the Bot isn't trained on any multichat Data, and [openassistant-guananco](https://huggingface.co/datasets/timdettmers/openassistant-guanaco) is really small, not really enough examples.~~
That was actually a bug on my end, its fixed and the chat is now really good!

This currently runs On GPU with vLLM, but it could also be run on a cpu with 2-4GB ram with a `Llama.cpp-python` for GGUF.

### CODE REVIEW

**Comment by VatsaDev** [comment]
Image example:
Screen Shot 2023-09-16 at 7 39 16 PM

**Comment by VatsaDev** [comment]
Image Example:
Screen Shot 2023-09-16 at 8 54 06 PM

**Comment by VatsaDev** [comment]
Also, be sure to enter your Ngrok auth token for colab, or it wont work

**Comment by gabrielgrant** [comment]
the colab notebook is failing for me with a cuda error when vllm tries to import cuda_utils:
```
ImportError: libcudart.so.12: cannot open shared object file: No such file or directory
```

<details>
<summary>
full traceback
</summary>

```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
[<ipython-input-2-4bae344bdc7c>](https://localhost:8080/#) in <cell line: 3>()
      1 from flask import Flask, render_template, request
      2 from flask_ngrok import run_with_ngrok
----> 3 from vllm import LLM, SamplingParams
      4 
      5 app = Flask(__name__, template_folder='/content/tinyLlamaChat')

3 frames
[/usr/local/lib/python3.10/dist-packages/vllm/__init__.py](https://localhost:8080/#) in <module>
      1 """vLLM: a high-throughput and memory-efficient inference engine for LLMs"""
      2 
----> 3 from vllm.engine.arg_utils import AsyncEngineArgs, EngineArgs
      4 from vllm.engine.async_llm_engine import AsyncLLMEngine
      5 from vllm.engine.llm_engine import LLMEngine

[/usr/local/lib/python3.10/dist-packages/vllm/engine/arg_utils.py](https://localhost:8080/#) in <module>
      4 from typing import Optional, Tuple
      5 
----> 6 from vllm.config import (CacheConfig, ModelConfig, ParallelConfig,
      7                          SchedulerConfig)
      8 

[/usr/local/lib/python3.10/dist-packages/vllm/config.py](https://localhost:8080/#) in <module>
      7 from vllm.logger import init_logger
      8 from vllm.transformers_utils.config import get_config
----> 9 from vllm.utils import get_cpu_memory
     10 
     11 logger = init_logger(__name__)

[/usr/local/lib/python3.10/dist-packages/vllm/utils.py](https://localhost:8080/#) in <module>
      6 import torch
      7 
----> 8 from vllm import cuda_utils
      9 
     10 

ImportError: libcudart.so.12: cannot open shared object file: No such file or directory

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
---------------------------------------------------------------------------
```

</details>

**Comment by VatsaDev** [comment]
@gabrielgrant thanks, I've incorporated all the changes, it works again!

**Comment by gabrielgrant** [comment]
saw this PR only removed the old HF chat link. would it make sense to add a link to this colab into the readme?

**Pull request closed without merging**
